### PR TITLE
FIX Regex rules are improved to not match commit prefixes in words

### LINKED ISSUE #86: Don't treat "Fixing" as a commit prefix
Some examples from changelogs in the wild:

```
2017-04-26 1ff6f3f1 ing doArchive (John Milmine)
2017-04-07 41eddfcc ing cms page history controller to use new page id param (Tim Kung)
2017-05-02 2187c160b ing pagination api doc typo (3Dgoo)
```

This happens when the commit messages start with `Fixing ...`.

Pretty low priority, but ideally the regex would match the words it looks for with a space or `:` afterwards, but not another letter.

The same thing would happen with `Fixes ...`

```
2017-02-09 6e2797ffc es for using dblib PDO driver. (Andrew O'Neil)
2016-12-08 dc530c0 es #529 (torleif)
```

### PR DESCRIPTION
**Pull request by robbieaverill**
For example, "Fixing foo" should not end up in the changelog as "ing foo", but FIX Fixing foo
should be  in the changelog as "Fixing foo"

Resolves #86

### CODE REVIEW

File: src/Model/Changelog/ChangelogItem.php [hunk 1]
```diff
@@ -70,17 +70,17 @@ public function setChangelogLibrary($changelogLibrary)
     protected static $types = array(
         'Security' => array(
             // E.g. "[ss-2015-016]: Security fix"
-            '/^(\[SS-2(\d){3}-(\d){3}\])\s?:?/i'
+            '/^(\[SS-2(\d){3}-(\d){3}\])\s?:?\s+/'
```
Comment (dhensby) [inline src/Model/Changelog/ChangelogItem.php]: All these regex expressions could be simplified by removing the `\s?:?\s+` and just replacing with `\b` (word boundary)

File: tests/Model/Changelog/ChangelogItemTest.php [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+        $this->assertSame($expected, $item->getShortMessage());
+    }
+
+    /**
+     * @return array[]
+     */
+    public function shortMessageProvider()
+    {
+        return [
+            ['BUG Entwine shouldn\'t use jQuery', 'Entwine shouldn\'t use jQuery'],
```
Comment (dhensby) [inline tests/Model/Changelog/ChangelogItemTest.php]: This generator uses different messages to the other which means I can't be sure they act as expected across both tests

File: src/Model/Changelog/ChangelogItem.php (hunk 1 above)
Comment (robbieaverill) [reply src/Model/Changelog/ChangelogItem.php]: Implemented in each rule other than this security one where word boundary matching didn't work (probably because of the brackets)
